### ISSUE TITLE
cannot understand the deduplication property

### ISSUE THREAD

**Issue by macit-emre** [tbela99/css#151]
when i use this style as inpu : 
`h1{
color:red!important;
}
h1{
color:blue;
}`
`$parser->parse()` method not gives me the line with !important, it gives this output
`h1{color:blue}`
as we see, code with !important should stay but it gives the non-important line in the compressed output, can you help me?

**Comment by tbela99** [comment]
this is the correct behavior

the result is 

```css

h1 {
color:red!important;
color:blue; 
}

```

only the last valid declaration with the same name will be applied which is color:blue; 

the finale result is 


```css

h1 {
color:blue; 
}

```
